server:
  port: 8090
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris: http://localhost:9200
